services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - rest-server
      - web

  rest-server:
    build:
      context: .
      dockerfile: ./rest-server/Dockerfile
    expose:
      - "8080"
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./rest-server:/app
      - cdn-data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    expose:
      - "4200:4200"
    restart: always
    volumes:
      - ./web:/app
    env_file:
      - ./.env

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-makkakuh}
    expose:
      - "5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  cdn-data: